substitutions:
  device: esp_air_freesh
  name: air-freesh
  friendly_name: Air Freesh
  model: AirWick
  location: ${friendly_name}
  location_low: ${name}
  update_interval: 15s
  fu_fu: 0.5s
  device_ip: 192.168.0.0
  sleep_interval: 15min
  night_coef: "2"
  sleep_coef: "1.06"
  discovery: "home/devices"
  comment: "Airfresh"

packages:
  airfresh: !include packages/air_freesh.yaml
