substitutions:
  device: esp_daikin_air_sensor
  name: daikin
  friendly_name: DAIKIN
  location: ${friendly_name}
  device_ip: 192.168.0.0
  reboot_timeout: 0s
  update_interval: 60s
  comment: "DAIKIN Air Sensor | BRY88AB151K"

<<: !include common/esp/esp32_node.yaml

<<: !include common/common.yaml

packages:
  common: !include packages/common_32.yaml
  daikin: !include packages/daikin_air_sensor.yaml
