substitutions:
  device: esp_music_leds_illumination
  name: music-leds-illumination
  friendly_name: Music Leds Illumination
  location: ${friendly_name}
  update_interval: 60s
  device_ip: 192.168.0.0
  reboot_timeout: 0s
  num_leds: "300"
  type_leds: "GRB"
  flagflip: "0"
  pin_leds: "GPIO16"
  color_correct_bright: "50%"
  sunrise: "600"  # 10 Minutes
  sunrize_bright: "255"  # Max brightness 0..255
  comment: "Illumination Light with Music Leds | Sound Reactive and Hyperion effects"

esphome:
  <<: !include common/boot/window_illumination.yaml

<<: !include common/esp/esp32_wrover.yaml

<<: !include common/common.yaml

packages:
  common: !include packages/common_32.yaml
  led_power: !include packages/led_power.yaml
  light: !include packages/neopixel_light.yaml
  lightcommon: !include packages/neopixel_light_common.yaml
  fastled: !include packages/neopixel_light_fastled.yaml
  musicleds: !include packages/neopixel_light_music_leds.yaml
  special: !include packages/neopixel_light_special.yaml
  sunrise: !include packages/neopixel_light_sunrise.yaml
  hyperion: !include packages/neopixel_light_ddp.yaml
