substitutions:
  device: esp_senseair_light
  name: senseair-light
  friendly_name: Senseair
  location: ${friendly_name}
  update_interval: 60s
  device_ip: 192.168.0.0
  reboot_timeout: 0s
  min_co2: "600"
  med_co2: "2000"
  num_leds: "8"
  flagflip: "0"
  type_leds: "GRB"
  pin_leds: "GPIO3"
  color_correct_bright: "100%"
  sunrise: "600"  # 10 Minutes
  sunrize_bright: "255"  # Max brightness 0..255
  project_name: "ajs.co2_light"
  project_version: "1.0.5"
  comment: "Senseair S8 Light"

<<: !include common/esp/esp8266_mini.yaml

<<: !include common/common.yaml

packages:
  common: !include packages/common_8266.yaml
  s8: !include packages/senseair_s8.yaml
  light: !include packages/neopixel_light.yaml
  lightcommon: !include packages/neopixel_light_common.yaml
  special: !include packages/neopixel_light_special.yaml

binary_sensor:
  # Workday
  - !include common/binary_sensor/workday.yaml

  # Night
  - !include common/binary_sensor/night.yaml

switch:
  # Automatic mode
  - !include common/switch/automatic.yaml
