# Common sensors for ESP32
esphome:
  name: $name
  friendly_name: $friendly_name
  comment: $comment
  build_path: ./.build/$device
  project:
    name: $project_name
    version: $project_version

binary_sensor:
  # ESP Status
  - !include ../common/binary_sensor/status.yaml

text_sensor:
  # ESPHome Version
  - !include ../common/text_sensor/version.yaml

  # Uptime
  - !include ../common/text_sensor/uptime.yaml

sensor:
  # Uptime
  - !include ../common/sensor/uptime.yaml

  # WiFi Signal
  - !include ../common/sensor/wifi-signal.yaml

  # ESP32 Internal Temperature
  - !include ../common/sensor/device_temperature.yaml

  # ESP32 Magnetic / Hall Sensor
  # - !include ../common/sensor/magnetic.yaml

switch:
  # Restart
  - !include ../common/switch/restart.yaml
