substitutions:
  project_name: "ajs.Light - Matrix Lamp"
  project_version: "1.1.5"

esphome:
  libraries:
    - fastled/FastLED @ 3.6.0
  includes:
    - includes/matrix_lamp/light.h
    - includes/matrix_lamp/common.h
    - includes/matrix_lamp/constants.h
    - includes/matrix_lamp/effect_data.h
    - includes/matrix_lamp/effect_palette.h
    - includes/matrix_lamp/effects.h
    - includes/matrix_lamp/noise_effects.h
    - includes/matrix_lamp/effect_ticker.h
    - includes/matrix_lamp/utility.h
    - includes/matrix_lamp/matrix_lamp.h

external_components:
  - source:
      type: git
      url: https://github.com/KaufHA/common
    components: [ddp]

ddp:

# Over The Air Update Component
ota:
  on_begin:
    then:
      - lambda: |-
          matrix_lamp.~GyverLamp();

switch:
  # Random Mode Settings
  - platform: template
    name: ${name} Random Mode
    icon: mdi:shuffle
    lambda: |-
      return matrix_lamp.GetRandomSettings();
    turn_on_action:
      - lambda: |-
          matrix_lamp.SetRandomSettings(true);
    turn_off_action:
      - lambda: |-
          matrix_lamp.SetRandomSettings(false);

number:
  # Matrix Orientation
  - platform: template
    name: ${name} Matrix Orientation
    icon: mdi:mdi-arrow-expand
    min_value: 1
    max_value: 8
    step: 1
    optimistic: true
    id: matrix_orientation
    initial_value: 3
    mode: slider
    entity_category: config
    disabled_by_default: true
    restore_value: true
    on_value:
      then:
      - lambda: |-
          matrix_lamp.SetMatrixOrientation(x);

  # FastLed Settings
  - !include ../common/number/fastled_speed.yaml
  - !include ../common/number/fastled_variant.yaml

light:
  # Neopixel with Matrix Lamp
  - !include ../common/light/neopixel_matrix_lamp.yaml
