substitutions:
  project_name: "ajs.Light"
  project_version: "1.5.5"

light:
  # Neopixel with Light
  - platform: neopixelbus
    id: neopixel_led
    type: ${type_leds}
    pin: ${pin_leds}
    num_leds: ${num_leds}
    name: ${name} NeoPixel
    icon: mdi:string-lights
    color_correct: [$color_correct_bright, $color_correct_bright, $color_correct_bright]
    variant: 800KBPS  # WS2812 (same as 800KBPS)
